apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-app-go
        image: localhost:5000/helloworld-go:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
      - name: hello-app-py
        image: localhost:5000/helloworld-py:latest
        ports:
        - containerPort: 6000
        env:
          - name: PORT
            value: "6000"
      - name: hello-app-js
        image: localhost:5000/helloworld-js:latest
        ports:
        - containerPort: 7000
        env:
          - name: PORT
            value: "7000"